import React,{useEffect,useRef,useState} from 'react';
import {registerPlugin,framely} from '@framely/sdk';
import {Button,Section,Slider,Toggle,Notice,Mark} from './ui';
import css from './style.css';
type Controls={hue:number;saturation:number;brightness:number};
type ColorControls={saturation:number;brightness:number;temperature:number};
const defaultColor:ColorControls={saturation:1,brightness:1,temperature:0};
const colorValues=({saturation,brightness,temperature}:ColorControls):ColorControls=>({saturation,brightness,temperature});
type State={mode:'off'|'color'|'mono'|null;modeError:string;colorAvailable:boolean;colorSettings:ColorControls&{enabled:boolean};colorNativeActive:boolean;colorSaturationReady:boolean;colorRestartRequired:boolean;settings:Controls&{enabled:boolean;originalHue:number|null};nativeActive:boolean;connected:boolean;supported:boolean|null;restartRequired:boolean;matchedMono:number;error:string};
const adjustmentValues=({hue,saturation,brightness}:Controls):Controls=>({hue,saturation,brightness});
function Page(){
 const[info,setInfo]=useState<State|null>(null),[draft,setDraft]=useState<Controls>({hue:.67,saturation:1,brightness:1}),[colorDraft,setColorDraft]=useState<ColorControls>(defaultColor),[error,setError]=useState(''),[saving,setSaving]=useState(false),[working,setWorking]=useState(false);
 const colorPending=useRef<ColorControls|null>(null),pending=useRef<Controls|null>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null),sending=useRef(false),alive=useRef(true),initialized=useRef(false);
 useEffect(()=>{alive.current=true;async function refresh(){try{const result=await framely.call<State>('status');if(alive.current){setInfo(result);if(!initialized.current){initialized.current=true;setDraft(adjustmentValues(result.settings));setColorDraft(colorValues(result.colorSettings??defaultColor));}}}catch(e){if(alive.current)setError(String(e));}}void refresh();const interval=setInterval(()=>void refresh(),2500);return()=>{alive.current=false;clearInterval(interval);if(timer.current)clearTimeout(timer.current);};},[]);
 async function flush(rethrow=false){if(sending.current)return;sending.current=true;setSaving(true);try{while(pending.current||colorPending.current){const mono=pending.current;const color=colorPending.current;const values=mono?adjustmentValues(mono):colorValues(color!);if(mono)pending.current=null;else colorPending.current=null;const result=await framely.call<State>(mono?'set':'color.set',values);if(alive.current){setInfo(result);setError('');}}}catch(e){pending.current=null;colorPending.current=null;if(alive.current)setError(String(e));if(rethrow)throw e;}finally{sending.current=false;if(alive.current)setSaving(false);}}
 function change(values:Controls){setDraft(values);pending.current=adjustmentValues(values);if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>void flush(),250);}
 function changeColor(values:ColorControls){setColorDraft(values);colorPending.current=colorValues(values);if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>void flush(),250);}
 async function action(method:string,params:unknown={}){if(timer.current)clearTimeout(timer.current);setWorking(true);setError('');try{while(sending.current)await new Promise(r=>setTimeout(r,30));if(pending.current||colorPending.current)await flush(true);while(sending.current)await new Promise(r=>setTimeout(r,30));const result=await framely.call<State>(method,params);if(alive.current){setInfo(result);setDraft(adjustmentValues(result.settings));setColorDraft(colorValues(result.colorSettings??defaultColor));}}catch(e){if(alive.current)setError(String(e));}finally{if(alive.current)setWorking(false);}}
 const colorBlocked=working||!info||!info.connected||info.supported===false;
 const blocked=working||!info||(info.settings.enabled&&(!info.connected||info.supported===false));
 return <main className="color-page"><header className="plugin-header color-header"><Mark/><div><h1>透视调色</h1><small>选择透视模式，调整更舒适的画面。</small></div></header><div className="plugin-content"><div className="mode-buttons" role="group" aria-label="透视模式">{([{id:'off',label:'关闭透视'},{id:'color',label:'彩色透视'},{id:'mono',label:'黑白透视'}] as const).map(mode=><Button key={mode.id} aria-pressed={info?.mode===mode.id} className={info?.mode===mode.id?'active':''} disabled={working||saving||!info?.mode||!info.connected||(mode.id==='color'&&!info.colorAvailable)} title={mode.id==='color'&&info&&!info.colorAvailable?'未检测到彩色透视相机':undefined} onClick={()=>void action('mode',{mode:mode.id})}>{mode.label}</Button>)}</div><p className={'connection '+(info?.connected?'connected':'')} role="status"><i/>{!info?'正在连接 SteamVR…':info.supported===false?'当前版本尚未适配':info.connected?'SteamVR 已连接':'等待 SteamVR 连接'}</p>{error&&<Notice error>{error}</Notice>}{info?.error&&<Notice error>{info.error}</Notice>}{info?.supported===false&&<Notice error>此 SteamVR 版本尚未适配，调色模块不会启用。</Notice>}
 {info?.modeError&&<Notice error>{info.modeError}</Notice>}
 {info?.mode==='color'&&<>
 <Section title="彩色透视调节"><Toggle label="启用彩色调节" checked={info.colorSettings.enabled} disabled={working||saving||!info.connected||info.supported===false} onChange={enabled=>void action('color.enable',{enabled})} description="单独保存彩色参数，停用后恢复原始彩色画面。"/>
 {info.colorRestartRequired&&<Notice>彩色模块将在下次 SteamVR 启动后加载。参数会保存，插件不会自动重启 SteamVR。</Notice>}
 {info.colorSettings.enabled&&info.colorNativeActive&&!info.colorSaturationReady&&<Notice>彩色亮度和冷暖模块已加载；饱和度需要受支持的彩色渲染路径加载后才能调整。</Notice>}
 <Slider label="亮度（%）" gradient="linear-gradient(to right, #111, #fff)" color={`hsl(0 0% ${colorDraft.brightness/1.5*100}%)`} value={Math.round(colorDraft.brightness*100)} min={25} max={150} disabled={colorBlocked} onChange={value=>changeColor({...colorDraft,brightness:value/100})}/>
 <Slider label="饱和度（%）" gradient="linear-gradient(to right, #808080, #e36744)" color={`hsl(15 ${colorDraft.saturation*50}% 58%)`} value={Math.round(colorDraft.saturation*100)} min={0} max={200} disabled={colorBlocked||!!info.colorSettings.enabled&&!info.colorSaturationReady} onChange={value=>changeColor({...colorDraft,saturation:value/100})}/>
 <Slider label="冷暖" gradient="linear-gradient(to right, #78afff, #eee, #ffc379)" color={`hsl(${colorDraft.temperature<0?215:35} ${Math.abs(colorDraft.temperature)*80}% 72%)`} value={Math.round(colorDraft.temperature*100)} min={-100} max={100} disabled={colorBlocked} onChange={value=>changeColor({...colorDraft,temperature:value/100})}/>
 <div className="temperature-ends"><small>偏冷</small><small>中性</small><small>偏暖</small></div><p className="save-state" role="status">{saving?'正在应用…':colorPending.current?'等待应用…':'设置自动保存'}</p>
 <div className="reset-row"><small>冷暖调整不代表经过校准的色温值。</small><Button disabled={colorBlocked||saving} onClick={()=>void action('color.reset')}>恢复原始彩色效果</Button></div></Section>
 </>}
 {info?.mode==='mono'&&<>
 <Section title="调色设置"><Toggle label="启用调色" checked={info?.settings.enabled??false} disabled={working||saving||!info||!info.connected||info.supported===false} onChange={enabled=>void action('enable',{enabled})} description={info?.settings.enabled?'停用后恢复启用前的色调与原始亮度。':'调整透视画面的色调、饱和度与亮度。'}/>
 {info?.restartRequired&&<Notice>首次启用的饱和度与亮度将在下次 SteamVR 启动后生效。色调可立即调整；插件不会自动重启 SteamVR。</Notice>}{info?.settings.enabled&&info.nativeActive&&<p className="status"><i/>调色模块已启用{info.matchedMono===0?' · 等待打开透视':''}</p>}
 <div className="tone-preview" style={{background:`hsl(${draft.hue*360} ${draft.saturation*70}% ${Math.min(75,45*draft.brightness)}%)`}}><span>色调示意</span></div>
 <Slider gradient="linear-gradient(to right, #f00, #ff0, #0f0, #0ff, #00f, #f0f, #f00)" color={`hsl(${draft.hue*360} 100% 50%)`} label="色相（°）" value={Math.round(draft.hue*360)} min={0} max={360} step={1} disabled={blocked||draft.saturation===0&&!!info?.nativeActive} onChange={degrees=>change({...draft,hue:degrees/360})}/>
 <Slider gradient={`linear-gradient(to right, hsl(${draft.hue*360} 0% 50%), hsl(${draft.hue*360} 70% 50%))`} color={`hsl(${draft.hue*360} ${draft.saturation*70}% 50%)`} label="染色饱和度（%）" value={Math.round(draft.saturation*100)} min={0} max={100} step={1} disabled={blocked} onChange={value=>change({...draft,saturation:value/100})}/>
 <Slider gradient={`linear-gradient(to right, hsl(${draft.hue*360} ${draft.saturation*70}% 11.25%), hsl(${draft.hue*360} ${draft.saturation*70}% 67.5%))`} color={`hsl(${draft.hue*360} ${draft.saturation*70}% ${45*draft.brightness}%)`} label="亮度（%）" value={Math.round(draft.brightness*100)} min={25} max={150} step={1} disabled={blocked} onChange={value=>change({...draft,brightness:value/100})}/>
 <p className="save-state" role="status">{saving?'正在应用…':pending.current?'等待应用…':'设置自动保存'}</p></Section>
 <Section title="预设"><div className="presets"><Button disabled={blocked} onClick={()=>change({...draft,saturation:0,brightness:1})}>中性黑白</Button><Button disabled={blocked} onClick={()=>change({hue:.08,saturation:.3,brightness:1})}>柔和暖色</Button><Button disabled={blocked} onClick={()=>change({hue:.58,saturation:.3,brightness:1})}>柔和冷色</Button></div><div className="reset-row"><small>恢复启用前的色调与原始增益。</small><Button disabled={blocked||saving} onClick={()=>void action('reset')}>恢复原始效果</Button></div></Section>
 <details className="help"><summary>如何调整</summary><p>先启用调色。首次启用后重新进入 SteamVR，看到“调色模块已启用”即可调节全部参数。以后调整不需要重启。</p><p>色调选择染色颜色；饱和度 0% 为中性黑白，100% 保留系统染色强度。黑白摄像头不会因此产生真实彩色画面。</p><p>亮度 100% 保持原始增益；高于 100% 可能让亮部丢失细节。中性黑白预设不修改摄像头或整个 Steam 界面的显示参数。</p><p>停用会恢复启用前的色调和原始饱和度、亮度，并取消下次启动的模块配置。卸载前请先停用；已载入的模块将在 SteamVR 下次关闭时退出。</p><p>设置会保存，并在插件启动后恢复。系统更新不匹配时会停止启用模块，等待插件适配。</p></details></>}</div></main>;
}
registerPlugin({QuickPage:Page});

const sheet=document.createElement('style');sheet.textContent=css;document.head.append(sheet);
